spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/smalleducator
    username: smalleducator
    password: wild-password
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG